<a href="https://colab.research.google.com/github/aadi0004/advanced-python/blob/main/2_1_25_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:





#

In [2]:
# Q.1 What is Pandas, and how is it different from NumPy?
# ans . pandas is a python language library that is used to manipulate the data
#       numpy works on mathematical data and used for mathematicl calculations
#       pandas has dataframe and numpy has arrays

In [3]:
# # Q.2 Explain the difference between a Series and a DataFrame in Pandas.
# ans.  series is a one dimentional array that show only values/rows and dataframe
#       is a two dimentional array that shows rows or columns both
#       to create series and dataframe we use
#       pd.Series() and pd.DataFrame()

In [6]:
# # Q.3 How can you create a DataFrame in Pandas from a dictionary?
# # ans
# data={
#       'name':['aadi','shiv'],
#       'age':[20,22]
#   }
# df=pd.DataFrame(data)

In [ ]:
# # Q.4 What is the purpose of the index in a Pandas DataFrame or Series?
# ans . index is uesd for loc and iloc function in python
#       and it uniquly identify rows and columns

In [ ]:
# # Q.5 How can you add a new column to an existing DataFrame?
# we can add column by dataframe name and [''] in this that columns name
# for example
# df['new_column']=[1,2,3]
# here we add new column in dataframe

In [ ]:
# # Q.6 Explain how you can delete a column or row from a DataFrame.
# df.drop('column_name',axis=1,inplace=True)
# df.drop('row_name',axis=0,inplace=True)
# axis=0 means row
# axis=1 means column
# inplace with change DataFrame

In [ ]:
# Q.7 What are the different ways to select subsets of data from a DataFrame?
# df['column_name'].value_counts()     ==> this will select each unique data
# df.loc['row_name']
# df.iloc[1:4]  ==> Rows 1 to 3
# df[['column1', 'column2']]

In [ ]:
# # Q.8 How do you handle missing data in Pandas?

# by droping or filling the missing data
# for droping we use df.dropna() ==> df is dataframe name
# for filling we use df.fillna(0) ==> fill all missing values with 0
# df['col'].fillna(df['col'].mean(), inplace=True)  # Mean value will be filled

In [ ]:
# # Q.9 How can you group data in a DataFrame and apply aggregate functions?
# by groupby function we can group data in dataframe and can apply aggregate functions
# for example
# df.groupby('col_name').mean()
# df.groupby('col_name').sum()
# df.groupby('col_name').max()
# df.groupby('col_name').min()
# df.groupby('col_name')['another_col'].count()

In [ ]:
# # Q.10 What is the difference between the apply(), map(), functions in Pandas?
# The apply() and map() functions in Pandas are used for applying functions to DataFrame or Series

# import pandas as pd
# s = pd.Series([1, 2, 3, 4])
# print(s.map(lambda x: x * 2))

# mapping = {1: 'one', 2: 'two', 3: 'three'}
# print(s.map(mapping))


# # Apply() function to a Series
# print(s.apply(lambda x: x**2))

In [7]:
#  Q.11 How does the merge() function in Pandas differ from the concat() function?
# both used for combining datasets or dataframes
# concat add data after 1 dataframe

import pandas as pd
df1 = pd.DataFrame({'id': [1, 2, 3], 'name': ['asd', 'Bob', 'aadi']})
df2 = pd.DataFrame({'id': [2, 3, 4], 'score': [85, 90, 75]})
result = pd.merge(df1, df2, on='id')
print(result)

   id  name  score
0   2   Bob     85
1   3  aadi     90

In [8]:
result = pd.concat([df1, df2])
result

   id  name  score
0   1   asd    NaN
1   2   Bob    NaN
2   3  aadi    NaN
0   2   NaN   85.0
1   3   NaN   90.0
2   4   NaN   75.0

In [11]:
# Q.12 What is the purpose of the pivot_table() function in Pandas?

import pandas as pd
data = {'Product': ['A', 'B', 'A'], 'Region': ['East', 'West', 'East'], 'Sales': [100, 200, 150]}
df = pd.DataFrame(data)
pivot = pd.pivot_table(df, values='Sales' , columns='Region')
print(pivot)

Region   East   West
Sales   125.0  200.0

In [17]:
# Q.13 Explain the difference between loc[] and iloc[] in Pandas.
# used to select subsets of data from a DataFrame or Series
# loc[] (Label-based Indexing)
# iloc[] (Integer-based Indexing)

import pandas as pd
data = {'A': [10, 20, 30], 'B': [40, 50, 60], 'C': [70, 80, 90]}
df = pd.DataFrame(data)

# Using loc[]
print(df.loc[0,'A'])

# Using iloc[]
print(df.iloc[0, 0])

10
10

In [ ]:
# Q.14 How can you sort a DataFrame by its index or values?
df.sort_index()  ==> sort  by indexing
df.sort_values('col_name')  ==> sort by values

In [ ]:
# Q.15 If you have a DataFrame with duplicate rows, how can you remove them?
# by using drop_duplicates() function we can remove duplicates
df.drop_duplicates()

In [19]:
# Q.16 How can you check the data types of each column in a DataFrame?
df.dtypes

A    int64
B    int64
C    int64
dtype: object

In [21]:
# Q.17 What methods can you use to get a quick statistical summary of a DataFrame?
df.describe()
# df.info()

          A     B     C
count   3.0   3.0   3.0
mean   20.0  50.0  80.0
std    10.0  10.0  10.0
min    10.0  40.0  70.0
25%    15.0  45.0  75.0
50%    20.0  50.0  80.0
75%    25.0  55.0  85.0
max    30.0  60.0  90.0

In [24]:
# Q.18 How can you count the number of unique values in a specific column?
df['A'].nunique()

3

In [30]:
# Q.19 How can you identify and filter rows based on a condition in a DataFrame?
data = {'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)

filtered_df = df[df['A'] > 2]
print(filtered_df)

   A   B
2  3  30
3  4  40
4  5  50

In [31]:
# Q.20 How can you count the number of unique values in a specific column?
df['A'].nunique()

5